import os, glob

configfile: "../config/config.json"

# Get custom parameters
input_fasta = config.get("input_fasta")  # path
step_size = config.get("step_size")  # int
chunks = config.get("chunks")  # True or None
chunk_size = config.get("chunk_size")  # int or None
#print(step_size, chunks, chunk_size, input_fasta)

include: "rules/download.smk"
include: "rules/snoBIRD.smk"
#include: "rules/target_prediction.smk"


rule all:
    """ Run SnoBIRD to predict C/D box snoRNA genes in a genomic sequence."""
    input:
        split_chr_dir = "data/references/genome_fa/"
    # Specify which output will be created depending on the user-defined params

rule all_downloads:
    """ Download all models that constitute SnoBIRD."""
    input:
        model1 = "data/references/models/snoBIRD_first_model.pt",
        model2 = "data/references/models/snoBIRD_second_model.pt"



