# Snakemake general parameters

jobs: 999
use-conda: True
conda-frontend: mamba
quiet: rules

# Snakemake cluster parameters
immediate-submit: True
rerun-triggers: mtime
cluster: 'python3 scripts/python/slurmSubmit.py {dependencies}' # script for sbatch jobs
cluster-config: '../profile_slurm/cluster.yaml' # config parameters for each rule
notemp: True
keep-going: True
